app/app_base/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from app_base import views
from calculation_engine import urls as ce_urls
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view
from calculation_engine.config import load_config_from_file

# # Imports for serving static files in development mode
# # ref: https://docs.djangoproject.com/en/4.2/howto/static-files/#serving-static-files-during-development
# from django.conf import settings
# from django.conf.urls.static import static

from calculation_engine.log import get_logger
logger = get_logger(__name__)


router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)

urlpatterns = [
    path('', views.HomePageView, name='home'),
    path('token', views.CustomAuthToken.as_view(), name='token'),
    path('request-access', views.RequestAccess.as_view(), name='request-access'),
    path('admin/', admin.site.urls, name='admin'),
    path('oidc/', include('mozilla_django_oidc.urls')),
    path('users/', views.UserListView.as_view(), name='user-list-page'),
    path('', include('users.urls')),
    path('api/v0/', include(router.urls), name='base-api'),
    path('api/v0/token/', views.get_token, name='token-api'),
    path('ce/', include(ce_urls.page_urlpatterns)),
    path('api/v0/ce/', include(ce_urls.api_urlpatterns)),
]
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config = load_config_from_file()
urlpatterns += [
    # Use the `get_schema_view()` helper to add a `SchemaView` to project URLs.
    #   * `title` and `description` parameters are passed to `SchemaGenerator`.
    #   * Provide view name for use with `reverse()`.
    path('openapi/', get_schema_view(
        title="MUSES Calculation Engine API",
        description="API for the MUSES Calculation Engine",
        version=config['version'],
        patterns=urlpatterns,
        public=True,
        # urlconf='app_base.urls',
    ), name='openapi-schema'),
    # ...
    # Route TemplateView to serve Swagger UI template.
    #   * Provide `extra_context` with view name of `SchemaView`.
    path('swagger-ui/', TemplateView.as_view(
        template_name='calculation_engine/swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
]

# Django Silk profiler (https://github.com/jazzband/django-silk)
# urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

app/calculation_engine/urls.py
from calculation_engine import views
from rest_framework import routers
from django.urls import path, include
from django.contrib.auth.decorators import login_required

job_api_router = routers.DefaultRouter()
job_api_router.register('', views.JobViewSet, basename='job')

upload_list = views.UploadViewSet.as_view({
    'get': 'list',
    'put': 'create'
})
upload_detail = views.UploadViewSet.as_view({
    'get': 'retrieve',
    'patch': 'partial_update',
    'delete': 'destroy'
})
upload_api_urlpatterns = [
    path('', upload_list, name='upload-list'),
    path('<str:pk>/', upload_detail, name='upload-detail'),
]
metrics_list = views.MetricViewSet.as_view({
    'get': 'list',
})
metrics_api_urlpatterns = [
    path('', metrics_list, name='metrics-list'),
]
api_urlpatterns = [
    path('job/', include(job_api_router.urls)),
    path('upload/', include(upload_api_urlpatterns)),
    path('metrics/', include(metrics_api_urlpatterns)),
    path('module/', views.ModuleListView, name='module-list-json'),
]

jobfile_detail = views.JobFileDownloadViewSet.as_view({
    'get': 'download',
    'post': 'download',
})

page_urlpatterns = [
    path('modules/', views.ModuleListView, name='module-list'),
    path('limits/', views.UsageLimitListView, name='limits-list'),
    path('jobs/', login_required(views.JobListView.as_view()), name='job-page'),
    path('uploads/', login_required(views.UploadListView.as_view()), name='upload-page'),
    path('metrics/', login_required(views.MetricListView.as_view()), name='metrics-page'),
    path('download/<uuid:job_id>/<path:file_path>', jobfile_detail, name='download-job-file'),
    path('download/<uuid:upload_id>', views.UploadDownloadViewSet.as_view({
        'get': 'download',
        'post': 'download',
    }), name='download-upload'),
]

app/users/urls.py
# users/urls.py
from django.urls import include
from django.urls import re_path

urlpatterns = [re_path(r"^accounts/", include("django.contrib.auth.urls"))]

app/calculation_engine/models.py
from django.db import models
import uuid
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
import hashlib

from calculation_engine.log import get_logger
logger = get_logger(__name__)


class Job(models.Model):
    class Meta:
        # -created means newest first
        # to avoid DRF pagination UnorderedObjectListWarning
        ordering = ['-created']
        # db_table = 'ce_jobs'
        verbose_name = _('job')
        verbose_name_plural = _('jobs')

    class JobStatus(models.TextChoices):
        '''
        Django docs: https://docs.djangoproject.com/en/5.0/ref/models/fields/#enumeration-types
        '''

        # Use the built-in Celery states
        PENDING = 'PENDING', _('Pending')
        STARTED = 'STARTED', _('Started')
        SUCCESS = 'SUCCESS', _('Success')
        FAILURE = 'FAILURE', _('Failure')
        RETRY = 'RETRY', _('Retry')
        REVOKED = 'REVOKED', _('Revoked')

    name = models.TextField(blank=True)
    description = models.TextField(blank=True)
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    error_info = models.TextField(blank=True)
    config = models.JSONField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Time Created')
    modified = models.DateTimeField(auto_now=True, verbose_name='Last Modified')
    uuid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        db_index=True,
        primary_key=True
    )
    status = models.CharField(
        max_length=10,
        choices=JobStatus.choices,
        default=JobStatus.PENDING,
    )
    saved = models.BooleanField(default=False, null=False, blank=True)
    public = models.BooleanField(default=False, null=False, blank=True)
    task_ids = models.JSONField(null=True, blank=True)
    current_processes = models.JSONField(default=list, blank=True)
    completed_processes = models.JSONField(default=list, blank=True)

    def __str__(self):
        ret = f'job: {self.uuid}, owner: {self.owner}, status: {self.status}'
        ret += f', created: {self.created}, config: {self.config}'
        return ret


class Metric(models.Model):
    time_collected = models.DateTimeField(auto_now_add=True, verbose_name='Time Collected')
    jobs_total = models.IntegerField(null=False, blank=False)
    jobs_success = models.IntegerField(null=False, blank=False)
    jobs_failure = models.IntegerField(null=False, blank=False)
    users_count = models.IntegerField(null=False, blank=False)
    users_active = models.IntegerField(null=False, blank=False)
    uploads_total = models.IntegerField(null=False, blank=False)
    uploads_size = models.BigIntegerField(null=False, blank=False)
    job_files_total = models.IntegerField(null=False, blank=False)
    job_files_size = models.BigIntegerField(null=False, blank=False)
    module_usage = models.JSONField(null=False, blank=False, default=dict)


def upload_dir_path(instance, filename):
    upload_path = f'''{instance.uuid}/{instance.path}'''
    # Calculate checksum
    data = instance.file.read()
    checksum = hashlib.md5(data).hexdigest()
    logger.debug(f'''"{upload_path}": {checksum}''')
    instance.checksum = checksum
    # Return upload path
    return upload_path


class Upload(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, db_index=True, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    path = models.CharField(max_length=None, default='')
    description = models.TextField(blank=True)
    file = models.FileField(upload_to=upload_dir_path, null=False, blank=False)
    owner = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    public = models.BooleanField(default=False, null=False, blank=True)
    size = models.BigIntegerField(null=False, blank=False, default=0)  # Size of the stored file in bytes
    checksum = models.CharField(max_length=32, blank=True, null=False, default='')

    def __str__(self):
        ret = f'path: {self.path}, description: {self.description}, public: {self.public}'
        ret += f', created: {self.created}'
        return ret


class JobFile(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    path = models.CharField(max_length=None, default='')
    size = models.BigIntegerField(null=False, blank=False, default=0) # Size of the stored file in bytes


def update_workflow_state(job_id, process_names=None, status=None):
    assert status in ['active', 'completed']
    assert process_names
    job = Job.objects.get(uuid__exact=job_id)
    # Append to list of active processes if not already in list
    if status == 'active':
        job.current_processes.extend([proc_name for proc_name in process_names
                                      if proc_name not in job.current_processes])
    if status == 'completed':
        # Remove from list of active processes
        for proc_name in process_names:
            try:
                job.current_processes.remove(proc_name)
            except Exception as err:
                logger.error(f'Ignoring error while removing process from current job processes: {err}')
        # Append to list of completed processes
        job.completed_processes.extend([proc_name for proc_name in process_names
                                        if proc_name not in job.completed_processes])
    job.save()


def update_job_state(job_id, state, error_info=''):
    logger.debug(f'''Updating job "{job_id}" state to: "{state}"...''')
    job = Job.objects.get(uuid__exact=job_id)
    job.status = state
    job.error_info = error_info
    # Forcibly clear current processes list
    if state in [Job.JobStatus.SUCCESS, Job.JobStatus.FAILURE]:
        job.current_processes = []
    job.save()

app/calculation_engine/templates/calculation_engine/home.html
{% extends 'app_base/base.html' %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row d-flex align-items-center">
    <!-- <div class="col-6">
      <div class="img-fluid p-3">
        <img src="{% static 'images/Muses_Full_Color_banner.png' %}" style="max-height: 5rem;" />
      </div>
    </div> -->
    <div class="col-12 align-items-center my-4">
      <img src="{% static 'images/Muses_Full_Color_banner.png' %}" 
      style="max-height: 5rem; display: inline-block; vertical-align: top; margin-right: 1rem;" />
      <span class="slogan">// Calculation Engine</span>
    </div>
  </div>
  <!-- <div class="row">
    <div class="">
    </div>
  </div> -->
  <div class="row pt-3">
    <div class="col-lg-6">
      <div class="get-started">
        <h3 class="mb-3">Getting started</h3>
        <p class="ps-4 lead">
          <i class="bi bi-book"></i> <a href="https://musesframework.io/docs/user/quickstart.html" target="_blank">Read the Quick Start guide</a> to setup your account and learn how to run workflows.
        </p>
        <p class="ps-4 lead">
          <i class="bi bi-life-preserver"></i> Join the discussion and ask for help <a href="https://forum.musesframework.io/new-topic?category=calc-engine-support&title=Replace%20me%20with%20descriptive%20title&body=Provide%20a%20detailed%20description%20of%20your%20problem%20and%20your%20question" target="_blank">
            on our community support forum</a>.
        </p>
        <p class="ps-4 lead">
          <i class="bi bi-blockquote-left"></i> Learn how to <a href="https://musesframework.io/docs/user/policies/citation.html" target="_blank">cite this software in your publications</a>.
        </p>

      </div>
      <h3 class="mb-3">What is the Calculation Engine?</h3>
      <p class="">
        The Calculation Engine is an application that lets you <b>run scientific calculations as composable workflows</b>, 
        constructed from a growing library of MUSES modules. The service hosted at 
        <a href="https://{{ url }}">https://{{ url }}</a> provides the research community with scalable, high-performance 
        computing resources to run intensive calculations. 
      </p>
      <p class="">
        <b><a href="https://gitlab.com/nsf-muses/calculation-engine" target="_blank">The Calculation Engine is free and open source software</a></b>, so if you are a interested in learning how to self-host the Calculation Engine on your own hardware, either for development purposes or to operate your own production instance, <a href="https://musesframework.io/docs/developer/calculation-engine.html" target="_blank">please see our developer documentation here.</a>
      </p>
      <h3 class="mb-3">What are MUSES modules?</h3>
      <p class="">
        <b>Modules are the atomic processing units of a MUSES workflow</b>. There are several types of modules, including those that calculate equations of state (EoS) and those that derive observable quantities from the EoS.
      </p>
      <p>The equation of state modules include:</p>
      <ul>
        {% for module in modules %}
        {% if module.type == "EoS" %}
        <li><b>{{ module.display_name }}</b> &ndash; <code>{{ module.name }} ({{ module.version }})</code></li>
        {% endif %}
        {% endfor %}
      </ul>
      <p>The observables modules include:</p>
      <ul>
        {% for module in modules %}
        {% if module.type == "Observable" %}
        <li><b>{{ module.display_name }}</b> &ndash; <code>{{ module.name }} ({{ module.version }})</code></li>
        {% endif %}
        {% endfor %}
      </ul>
      <p><b><a href="{% url 'module-list' %}"> <i class="bi bi-list-ul"></i> Visit this page</a> to view a more detailed list of registered modules.</b></p>

    </div>
    <div class="col-lg-6">
      <h3 class="mb-3">What are workflows?</h3>
      <p>MUSES workflows provide a way to orchestrate a custom execution of MUSES modules, allowing you to generate equations of state,
        process and synthesize data, and calculate observable quantities. Individual workflow executions are called jobs, which you can run concurrently
        on our performant compute nodes to generates reproducible results to download and analyze. <a href="https://musesframework.io/docs/user/workflows.html">Learn more about MUSES workflows here.
        <img src="/static/images/workflow_crust_chiral_cmf_lepton_synthesis_qlimr.drawio.png" style="max-width: 100%;" class="m-3">
        </a>
      </p>
      <h3 class="mb-3">What is MUSES?</h3>
      <p class="">
        <a href="https://musesframework.io">MUSES</a> is an <b>interdisciplinary team</b> of physics experts in lattice QCD,
        nuclear physics, gravitational wave astrophysics, relativistic
        hydrodynamics, and research software engineers. The goal of the
        collaboration is to help <b>find answers to questions that bridge nuclear
        physics, heavy-ion physics, and gravitational phenomena</b> such as: 
      </p>
      <ul>
        <li>
          What exists within the core of a neutron star?
        </li>
        <li>
          What temperatures are reached when two neutron stars collide?
        </li>
        <li>
          What can nuclear experiments with heavy-ion collisions teach us about the strongest force in nature and neutron stars?
        </li>
      </ul>
    </div>
  </div>

  <div class="row pt-3">
    <div class="col-lg-6">
    </div>
    <div class="col-lg-6">
    </div>








  </div>
</div>

{% endblock %}

app/calculation_engine/templates/calculation_engine/job_list.html
{% extends 'app_base/base.html' %}
{% block content %}
  <h1>Jobs</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Time Created (UTC)</th>
          <th>UUID</th>
          <th>Status</th>
          <th>Active processes</th>
          <th>Saved</th>
          <th>Public</th>
          <th>Error</th>
          {% if user.is_superuser %}
          <th>Owner</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% if job_list %}
        {% for this_job in job_list %}
        <tr>
          <td>{{ this_job.name }}</td>
          <td>{{ this_job.created|date:'Y/m/d H:i:s' }}</td>
          <td class="uuid-table"><code>{{ this_job.uuid }}</code></td>
          <td>{{ this_job.status }}</td>
          {% if this_job.current_processes %}
          <td class="uuid-table"><code>{{ this_job.current_processes|escapeseq|join:", " }}</code></td>
          {% else %}
          <td>None</td>
          {% endif %}
          <td>{{ this_job.saved }}</td>
          <td>{{ this_job.public }}</td>
          {% if this_job.error_info %}
          <td>
            <div class="error-msg"><code>{{ this_job.error_info }}</code></div>
          </td>
          {% else %}
          <td></td>
          {% endif %}
          {% if user.is_superuser %}
          <td>{{ this_job.owner }}</td>
          {% endif %}
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
  </table>
{% endblock %}

app/calculation_engine/templates/calculation_engine/limits.html
{% extends 'app_base/base.html' %}
{% load static %}
{% block title %}Usage Limits{% endblock %}
{% block additional_css %}
<style>
  td {
    max-width: 30rem;
  }
  td.narrow {
    max-width: 10rem;
  }
</style>
{% endblock %}

{% block content %}

<div class="container">
  <div class="row pt-3">
    <div class="col-lg-6">
      <h3>Usage Limits</h3>
      <p class="">
        The table below displays your usage limits.
      </p>
    </div>
  </div>
  <table class="table table-responsive">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Limit</th>
      </tr>
    </thead>
    <tbody>
      {% for key, limit in limits.items %}
      <tr>
        <td class="narrow">
          {{ limit.title }}
        </td>
        <td class="">
          {{ limit.description }}
        </td>
        <td class="narrow">
          <code>{{ limit.limit }}</code>
        </td>
      </tr>
     {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

app/calculation_engine/templates/calculation_engine/metrics.html
{% extends 'app_base/base.html' %}
{% block content %}
  <h1>Metrics</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Time</th>
          <th>Jobs (success/failure)</th>
          <th>Job files (size)</th>
          <th>Uploads</th>
          <th>Users (active)</th>
          <th>Users (total)</th>
        </tr>
      </thead>
      <tbody>
        {% if metric_list %}
        {% for this_metric in metric_list %}
        <tr>
          <td class="uuid-table"><code>{{ this_metric.time_collected }}</code></td>
          <td class="uuid-table"><code>{{ this_metric.jobs_total }} ({{ this_metric.jobs_success }}/{{ this_metric.jobs_failure }})</code></td>
          <td class="uuid-table"><code>{{ this_metric.job_files_total }} ({{ this_metric.job_files_size }} {{ this_metric.job_files_size_units }})</code></td>
          <td class="uuid-table"><code>{{ this_metric.uploads_total }}</code></td>
          <td class="uuid-table"><code>{{ this_metric.users_active }}</code></td>
          <td class="uuid-table"><code>{{ this_metric.users_count}}</code></td>
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
  </table>

{% endblock %}

app/calculation_engine/templates/calculation_engine/modules.html
{% extends 'app_base/base.html' %}
{% load static %}

{% block additional_css %}
<style>
  td.mono {
    max-width: 30rem;
    page-break-inside: avoid;
    font-family: monospace;
    overflow: hidden;
  }
  td.mono.narrow {
    max-width: 10rem;
  }
</style>
{% endblock %}

{% block content %}

<div class="container">
  <div class="row pt-3">
    <div class="col-lg-6">
      <h3>Modules</h3>
      <p class="">
        The table below displays the list of registered modules that can be included in workflows in this version of the Calculation Engine (<code>{{ version }}</code>).
      </p>
    </div>
  </div>
  <table class="table table-responsive">
    <thead>
      <tr>
        <th scope="col">Name / Docs</th>
        <th scope="col">Version / Source</th>
        <th scope="col">Container Image URL</th>
      </tr>
    </thead>
    <tbody>
      {% for module in modules %}
      <tr>
        
        <td class="mono narrow">
          <a class="nav-link" href="{{ module.docs_source_url }}">
            <i class="bi bi-journal-code"></i> {{module.name}}
          </a>
        </td>
        <td class="mono narrow">
          <a class="nav-link" href="{{module.repository_url}}/tree/{{module.version}}">
            <i class="bi bi-file-earmark-code"></i> {{module.version}}
          </a>
        </td>
        <td class="mono">
          <i class="bi bi-stack"></i> {{module.image_url}}
        </td>
      </tr>
     {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

app/calculation_engine/templates/calculation_engine/swagger-ui.html
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>

app/calculation_engine/templates/calculation_engine/upload_list.html
{% extends 'app_base/base.html' %}
{% block content %}
  <h1>Uploaded files</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Path</th>
          <th>Description</th>
          <th>Checksum</th>
          <th>UUID</th>
          <th>Time Uploaded</th>
          <th>Public</th>
          <th>Link</th>
          {% if user.is_superuser %}
          <th>Owner</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% if upload_list %}
        {% for this_upload in upload_list %}
        <tr>
          <td class="uuid-table"><code>{{ this_upload.path }}</code></td>
          <td class="">{{ this_upload.description }}</td>
          <td class="uuid-table"><code>{{ this_upload.checksum }}</code></td>
          <td class="uuid-table"><code>{{ this_upload.uuid }}</code></td>
          <td>{{ this_upload.created }}</td>
          <td>{{ this_upload.public }}</td>
          <td>
            <form action="{% url 'download-upload' this_upload.uuid %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-link" style="padding: 0;">Download</button>
            </form>
          </td>
          {% if user.is_superuser %}
          <td>{{ this_upload.owner }}</td>
          {% endif %}
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
  </table>

{% endblock %}